/* ==========================================================================
   data.js — Static roadmap content (source of truth for structure/content).
   Nothing in this file is user progress — that lives in storage.js/state.
   ========================================================================== */

const PHASES = [
  { id: 1, name: "Python Foundations", weeks: [1, 2], projectIds: [] },
  { id: 2, name: "Build Simple Python Apps", weeks: [3], projectIds: [1, 2] },
  { id: 3, name: "API / FastAPI", weeks: [4, 5], projectIds: [] },
  { id: 4, name: "Build Your First API-Powered App", weeks: [6], projectIds: [3] },
  { id: 5, name: "SQL + Database", weeks: [7, 8], projectIds: [] },
  { id: 6, name: "Build Your First End-to-End App", weeks: [9], projectIds: [4] },
  { id: 7, name: "Machine Learning", weeks: [10, 11, 12, 13], projectIds: [5, 6] },
  { id: 8, name: "Deep Learning", weeks: [14, 15, 16, 17], projectIds: [7, 8] },
  { id: 9, name: "Generative AI — Non-Agentic", weeks: [18, 19, 20, 21], projectIds: [9, 10] },
  { id: 10, name: "Generative AI — Agentic", weeks: [22, 23, 24, 25], projectIds: [11, 12] },
];

// task cat: 'learning' | 'practice' | 'build'
const WEEKS = [
{ id:1, phaseId:1, title:"Python Core Syntax & Control Flow",
  goal:"Write a short Python script from a blank file — variables, the right data types, conditional logic — without pausing to look up basic syntax.",
  projectId:null,
  tasks:[
    {id:"w1t1",cat:"learning",label:"Variables, data types (int/float/str/bool/None) & type conversion"},
    {id:"w1t2",cat:"learning",label:"Operators: arithmetic, comparison, logical"},
    {id:"w1t3",cat:"learning",label:"Conditional statements: if / elif / else"},
    {id:"w1t4",cat:"learning",label:"input() and formatted print() / f-strings"},
    {id:"w1t5",cat:"practice",label:"Even/odd checker, calculator, °C↔°F converter"},
    {id:"w1t6",cat:"practice",label:"Grade classifier using if/elif/else"},
    {id:"w1t7",cat:"build",label:"Mini build: BMI Calculator (input → category)"},
    {id:"w1t8",cat:"build",label:"Initialize Git repo, first commit"},
  ],
  exitCriteria:[
    {id:"w1e1",label:"Can explain the difference between = and =="},
    {id:"w1e2",label:"Can write an if/elif/else chain without references"},
    {id:"w1e3",label:"Can read user input and safely convert its type"},
    {id:"w1e4",label:"Repo initialized and today's work committed"},
  ]},
{ id:2, phaseId:1, title:"Loops, Functions & Collections",
  goal:"Break a problem into functions and choose the right collection (list, tuple, dict) for the data you're holding.",
  projectId:null,
  tasks:[
    {id:"w2t1",cat:"learning",label:"while / for loops, break / continue"},
    {id:"w2t2",cat:"learning",label:"Functions: def, params, return, default args, scope"},
    {id:"w2t3",cat:"learning",label:"Lists, tuples, dictionaries — creation, indexing, iteration"},
    {id:"w2t4",cat:"learning",label:"Nesting collections (list of dicts, dict of lists)"},
    {id:"w2t5",cat:"practice",label:"FizzBuzz, multiplication table generator"},
    {id:"w2t6",cat:"practice",label:"Refactor Week 1 scripts into functions"},
    {id:"w2t7",cat:"build",label:"Mini build: Contact Book CLI (list of dicts: add/search/delete)"},
  ],
  exitCriteria:[
    {id:"w2e1",label:"Can write and call a function with params + return value"},
    {id:"w2e2",label:"Can explain when to use list vs tuple vs dict"},
    {id:"w2e3",label:"Can iterate/modify a list of dictionaries unaided"},
    {id:"w2e4",label:"Contact Book supports add, search, delete correctly"},
  ]},
{ id:3, phaseId:2, title:"Applying Python: Two Complete CLI Programs",
  goal:"Take a plain-English requirements list and turn it into a complete, working Python program using functions and dictionaries — independently.",
  projectId:1,
  tasks:[
    {id:"w3t1",cat:"learning",label:"Organizing a program into functions before the main loop"},
    {id:"w3t2",cat:"learning",label:"Input validation basics; formatted/aligned printing"},
    {id:"w3t3",cat:"practice",label:"Pseudocode the data model for both projects before coding"},
    {id:"w3t4",cat:"practice",label:"Write & test calculation helpers in isolation first"},
    {id:"w3t5",cat:"build",label:"Build Project 1 — Student Report Card Generator"},
    {id:"w3t6",cat:"build",label:"Build Project 2 — Personal Expense Tracker (v1)"},
  ],
  exitCriteria:[
    {id:"w3e1",label:"Report Card Generator computes average & grade for multiple students"},
    {id:"w3e2",label:"Expense Tracker computes total, highest, and filters by category"},
    {id:"w3e3",label:"Both programs handle at least one bad-input case without crashing"},
    {id:"w3e4",label:"Both committed to Git with a working sample run"},
  ]},
{ id:4, phaseId:3, title:"API Fundamentals & Consuming APIs",
  goal:"Explain the request/response cycle and consume any documented REST API from Python, handling failures gracefully.",
  projectId:null,
  tasks:[
    {id:"w4t1",cat:"learning",label:"What an API is; client-server model"},
    {id:"w4t2",cat:"learning",label:"HTTP methods, status codes, JSON structure, headers"},
    {id:"w4t3",cat:"learning",label:"Query params vs path params vs request body"},
    {id:"w4t4",cat:"practice",label:"Hit a public API via curl, then via Python requests"},
    {id:"w4t5",cat:"practice",label:"Deliberately hit a bad endpoint, inspect the error"},
    {id:"w4t6",cat:"build",label:"Mini build: script fetching + printing public API data with graceful fallback"},
  ],
  exitCriteria:[
    {id:"w4e1",label:"Can explain the request/response cycle incl. status codes"},
    {id:"w4e2",label:"Can parse a JSON response in Python and extract fields"},
    {id:"w4e3",label:"Handles a failed request without crashing"},
  ]},
{ id:5, phaseId:3, title:"Building APIs with FastAPI",
  goal:"Design and implement a REST endpoint from scratch — including request validation — and test it without help.",
  projectId:null,
  tasks:[
    {id:"w5t1",cat:"learning",label:"What FastAPI is; path operations"},
    {id:"w5t2",cat:"learning",label:"Path/query params; request bodies via Pydantic models"},
    {id:"w5t3",cat:"learning",label:"Auto docs (Swagger/OpenAPI); status codes & error handling"},
    {id:"w5t4",cat:"practice",label:"Build 4 tiny endpoints (hello, echo, calculator, filtered GET)"},
    {id:"w5t5",cat:"build",label:"Mini build: Unit Converter / Quote-of-the-Day service (2-3 endpoints)"},
  ],
  exitCriteria:[
    {id:"w5e1",label:"Can define a Pydantic model FastAPI validates automatically"},
    {id:"w5e2",label:"Can explain what the Swagger docs are showing"},
    {id:"w5e3",label:"Can build a new endpoint from a plain-English spec unaided"},
  ]},
{ id:6, phaseId:4, title:"Project: Expense Tracker, API Version",
  goal:"Re-architect a CLI app as a REST API with proper request/response models.",
  projectId:3,
  tasks:[
    {id:"w6t1",cat:"learning",label:"Structuring a small FastAPI project; designing a REST resource"},
    {id:"w6t2",cat:"practice",label:"Sketch the API contract before writing endpoint code"},
    {id:"w6t3",cat:"build",label:"Build Project 3 — Expense Tracker API Version"},
    {id:"w6t4",cat:"build",label:"Postman collection covering every route incl. failure cases"},
  ],
  exitCriteria:[
    {id:"w6e1",label:"Week 3 expense logic now lives entirely behind HTTP endpoints"},
    {id:"w6e2",label:"Every endpoint validates input and returns correct status codes"},
    {id:"w6e3",label:"Postman collection demonstrates success and failure cases"},
  ]},
{ id:7, phaseId:5, title:"SQL Fundamentals",
  goal:"Write SELECT/WHERE/ORDER BY queries confidently from a plain-English question, without help.",
  projectId:null,
  tasks:[
    {id:"w7t1",cat:"learning",label:"Install PostgreSQL or MySQL"},
    {id:"w7t2",cat:"learning",label:"Create database, create first table"},
    {id:"w7t3",cat:"learning",label:"INSERT data; SELECT data"},
    {id:"w7t4",cat:"learning",label:"WHERE; ORDER BY"},
    {id:"w7t5",cat:"learning",label:"GROUP BY; aggregate functions"},
    {id:"w7t6",cat:"practice",label:"Practice 10 SQL queries against a 15+ row students table"},
    {id:"w7t7",cat:"build",label:"Mini challenge: SQL query set (grade>80, avg<25, 100% in Maths, order by avg)"},
  ],
  exitCriteria:[
    {id:"w7e1",label:"Can create a database"},
    {id:"w7e2",label:"Can create tables"},
    {id:"w7e3",label:"Can insert records"},
    {id:"w7e4",label:"Can query records"},
    {id:"w7e5",label:"Can filter records (WHERE)"},
    {id:"w7e6",label:"Can sort records (ORDER BY)"},
    {id:"w7e7",label:"Can group records (GROUP BY)"},
    {id:"w7e8",label:"Can use aggregate functions"},
    {id:"w7e9",label:"Completed the SQL challenge"},
  ]},
{ id:8, phaseId:5, title:"CRUD, Aggregates, Keys & Python↔DB Integration",
  goal:"Perform full CRUD from Python against a real database and explain why primary keys and relationships matter.",
  projectId:null,
  tasks:[
    {id:"w8t1",cat:"learning",label:"UPDATE / DELETE — completing CRUD"},
    {id:"w8t2",cat:"learning",label:"Primary keys; basic relationships (foreign keys, one-to-many)"},
    {id:"w8t3",cat:"learning",label:"Database design fundamentals"},
    {id:"w8t4",cat:"learning",label:"Connecting Python to the DB (psycopg2 / mysql-connector / SQLAlchemy)"},
    {id:"w8t5",cat:"practice",label:"Add a related second table and write a JOIN"},
    {id:"w8t6",cat:"build",label:"Mini build: Python script performing full CRUD against the real DB"},
  ],
  exitCriteria:[
    {id:"w8e1",label:"Can perform Create, Read, Update, Delete from Python"},
    {id:"w8e2",label:"Can write a GROUP BY query with an aggregate function"},
    {id:"w8e3",label:"Can explain why a table needs a primary key"},
  ]},
{ id:9, phaseId:6, title:"Project: Expense Tracker, API + Database Version",
  goal:"Demonstrate — and explain — the complete Python → FastAPI → Database flow, the template for every backend from here on.",
  projectId:4,
  tasks:[
    {id:"w9t1",cat:"learning",label:"Config/credential management (.env + python-dotenv)"},
    {id:"w9t2",cat:"learning",label:"Wiring FastAPI to a real DB (dependency-injected session)"},
    {id:"w9t3",cat:"practice",label:"Migrate the expenses table schema before touching endpoint code"},
    {id:"w9t4",cat:"build",label:"Build Project 4 — Expense Tracker API + Database Version"},
    {id:"w9t5",cat:"build",label:"Restart server, re-run Postman collection to verify persistence"},
  ],
  exitCriteria:[
    {id:"w9e1",label:"Data survives a server restart"},
    {id:"w9e2",label:"Every Week 6 endpoint reads/writes the real database"},
    {id:"w9e3",label:"Can explain the flow end to end: request → DB row → response"},
  ]},
{ id:10, phaseId:7, title:"ML Foundations & Regression Basics",
  goal:"Train and evaluate a basic linear regression model with scikit-learn independently.",
  projectId:null,
  tasks:[
    {id:"w10t1",cat:"learning",label:"Supervised vs unsupervised learning; regression as a category"},
    {id:"w10t2",cat:"learning",label:"Features vs labels; train/test split and why it matters"},
    {id:"w10t3",cat:"learning",label:"Cost functions & MSE, conceptually; scikit-learn fit/predict"},
    {id:"w10t4",cat:"practice",label:"Load a toy dataset with pandas, inspect it (head/describe)"},
    {id:"w10t5",cat:"build",label:"Mini build: baseline regression end to end on a provided CSV"},
  ],
  exitCriteria:[
    {id:"w10e1",label:"Can explain train/test split and why it matters"},
    {id:"w10e2",label:"Can train & evaluate a linear regression with scikit-learn unaided"},
  ]},
{ id:11, phaseId:7, title:"Project: Student Score Predictor (Regression)",
  goal:"Take a fresh input, run it through a trained model, and justify the prediction with real evaluation metrics.",
  projectId:5,
  tasks:[
    {id:"w11t1",cat:"learning",label:"Data cleansing basics (missing/invalid values)"},
    {id:"w11t2",cat:"learning",label:"Feature selection beyond one variable; R² and MAE"},
    {id:"w11t3",cat:"practice",label:"Clean a messier dataset; engineer 1-2 extra features"},
    {id:"w11t4",cat:"build",label:"Build Project 5 — Student Score Predictor"},
  ],
  exitCriteria:[
    {id:"w11e1",label:"Accepts new user input and returns a predicted score"},
    {id:"w11e2",label:"Reports at least two evaluation metrics"},
    {id:"w11e3",label:"Can explain what the metrics say about model quality"},
  ]},
{ id:12, phaseId:7, title:"Classification Foundations",
  goal:"Build a minimal text-classification pipeline — raw text to vector to trained model — independently.",
  projectId:null,
  tasks:[
    {id:"w12t1",cat:"learning",label:"Classification vs regression"},
    {id:"w12t2",cat:"learning",label:"Text preprocessing (lowercase, punctuation, stopwords)"},
    {id:"w12t3",cat:"learning",label:"Bag-of-Words / TF-IDF; Naive Bayes / Logistic Regression for text"},
    {id:"w12t4",cat:"practice",label:"Vectorize sample sentences; train a small classifier"},
    {id:"w12t5",cat:"build",label:"Mini build: classify 10-15 hand-written sentences with TF-IDF + LogisticRegression"},
  ],
  exitCriteria:[
    {id:"w12e1",label:"Can explain why raw text can't go directly into most ML models"},
    {id:"w12e2",label:"Can build a text → vector → model pipeline unaided"},
  ]},
{ id:13, phaseId:7, title:"Project: Spam Classifier & ML Phase Wrap",
  goal:"Build a complete classical ML classification pipeline from raw text to an evaluated model, and correctly interpret precision/recall.",
  projectId:6,
  tasks:[
    {id:"w13t1",cat:"learning",label:"Precision, recall, confusion matrix — why accuracy alone misleads"},
    {id:"w13t2",cat:"practice",label:"Evaluate with a full confusion matrix; discuss FP vs FN cost"},
    {id:"w13t3",cat:"build",label:"Build Project 6 — Spam Email/SMS Classifier"},
  ],
  exitCriteria:[
    {id:"w13e1",label:"Reports accuracy, precision, recall, confusion matrix"},
    {id:"w13e2",label:"Can explain when precision or recall matters more, in context"},
    {id:"w13e3",label:"Correctly classifies a deliberately tricky new message"},
  ]},
{ id:14, phaseId:8, title:"Neural Network Foundations",
  goal:"Describe what happens in a forward pass and why activation/loss functions are needed; comfortable with basic Keras Sequential.",
  projectId:null,
  tasks:[
    {id:"w14t1",cat:"learning",label:"Neurons, layers, weights & biases"},
    {id:"w14t2",cat:"learning",label:"Activation functions (ReLU, sigmoid, softmax)"},
    {id:"w14t3",cat:"learning",label:"Loss functions; gradient descent/backprop, conceptually"},
    {id:"w14t4",cat:"practice",label:"Trace a forward pass by hand on a tiny 2-input network"},
    {id:"w14t5",cat:"build",label:"Mini build: minimal Keras Sequential model on a toy dataset"},
  ],
  exitCriteria:[
    {id:"w14e1",label:"Can describe what a forward pass computes and why nonlinearity matters"},
    {id:"w14e2",label:"Comfortable building/compiling/fitting a basic Keras Sequential model"},
  ]},
{ id:15, phaseId:8, title:"Project: Handwritten Digit Recognizer (MNIST)",
  goal:"Train, evaluate, and improve a neural network on a real image dataset; read a training curve for over/underfitting.",
  projectId:7,
  tasks:[
    {id:"w15t1",cat:"learning",label:"Image data as tensors; normalization"},
    {id:"w15t2",cat:"learning",label:"Softmax for multi-class output; categorical cross-entropy"},
    {id:"w15t3",cat:"practice",label:"Load & visualize MNIST samples; build a baseline dense network"},
    {id:"w15t4",cat:"build",label:"Build Project 7 — Handwritten Digit Recognizer"},
  ],
  exitCriteria:[
    {id:"w15e1",label:"Model reaches roughly 90%+ test accuracy"},
    {id:"w15e2",label:"Can identify over/underfitting from the training curve"},
    {id:"w15e3",label:"Can show and explain a misclassified example"},
  ]},
{ id:16, phaseId:8, title:"Sequence Data & Text for Deep Learning",
  goal:"Explain why word order matters for text and build a minimal Embedding→LSTM pipeline, independently.",
  projectId:null,
  tasks:[
    {id:"w16t1",cat:"learning",label:"Tokenization; padding sequences"},
    {id:"w16t2",cat:"learning",label:"Word embeddings (concept + Embedding layer)"},
    {id:"w16t3",cat:"learning",label:"RNN/LSTM intuition vs TF-IDF from Week 12"},
    {id:"w16t4",cat:"practice",label:"Tokenize/pad a small dataset; build a toy Embedding→LSTM model"},
    {id:"w16t5",cat:"build",label:"Mini build: sentiment-classify 15-20 hand-written sentences with a tiny LSTM"},
  ],
  exitCriteria:[
    {id:"w16e1",label:"Can explain what an embedding layer does conceptually"},
    {id:"w16e2",label:"Can explain why LSTM captures more meaning than TF-IDF counts"},
    {id:"w16e3",label:"Toy LSTM classifier runs end to end"},
  ]},
{ id:17, phaseId:8, title:"Project: Sentiment Analysis & Deep Learning Phase Wrap",
  goal:"Build, train, and evaluate an RNN/LSTM text classifier end to end; articulate when DL is worth its complexity vs classical ML.",
  projectId:8,
  tasks:[
    {id:"w17t1",cat:"learning",label:"Avoiding overfitting: dropout, early stopping"},
    {id:"w17t2",cat:"practice",label:"Compare this model's metrics against Week 13's classical model"},
    {id:"w17t3",cat:"build",label:"Build Project 8 — Sentiment Analysis"},
  ],
  exitCriteria:[
    {id:"w17e1",label:"Model trains/evaluates end to end with full metric suite"},
    {id:"w17e2",label:"Can articulate one concrete reason to choose DL vs classical ML for text"},
  ]},
{ id:18, phaseId:9, title:"LLM Foundations & Prompt Engineering",
  goal:"Call an LLM API from Python and write zero-shot, few-shot, and chain-of-thought prompts appropriately.",
  projectId:null,
  tasks:[
    {id:"w18t1",cat:"learning",label:"What an LLM is; pretraining vs fine-tuning, conceptually"},
    {id:"w18t2",cat:"learning",label:"Tokens, context windows"},
    {id:"w18t3",cat:"learning",label:"Zero-shot, few-shot, chain-of-thought prompting"},
    {id:"w18t4",cat:"practice",label:"Send the same task with all 3 prompt styles; compare outputs"},
    {id:"w18t5",cat:"build",label:"Mini build: prompt-comparison script with written observations"},
  ],
  exitCriteria:[
    {id:"w18e1",label:"Can call an LLM API from Python and handle the response"},
    {id:"w18e2",label:"Can write zero-shot/few-shot/CoT prompts and explain the difference in results"},
  ]},
{ id:19, phaseId:9, title:"Project: Resume Screening Application",
  goal:"Design prompts that reliably extract structured data from free text; build decision logic on top of that structured output.",
  projectId:9,
  tasks:[
    {id:"w19t1",cat:"learning",label:"Structured extraction via LLM (reliable JSON output)"},
    {id:"w19t2",cat:"practice",label:"Iterate an extraction prompt until it reliably returns clean JSON"},
    {id:"w19t3",cat:"build",label:"Build Project 9 — Resume Screening Application"},
  ],
  exitCriteria:[
    {id:"w19e1",label:"Extraction prompt reliably returns valid JSON across resumes"},
    {id:"w19e2",label:"Decision logic references real extracted fields"},
    {id:"w19e3",label:"Handles a malformed resume without crashing"},
  ]},
{ id:20, phaseId:9, title:"RAG Foundations: Embeddings, Chunking & Vector Search",
  goal:"Chunk, embed, store, and retrieve top-k results independently — the retrieval half of RAG, isolated from generation.",
  projectId:null,
  tasks:[
    {id:"w20t1",cat:"learning",label:"Embeddings, vectorization; chunking strategies"},
    {id:"w20t2",cat:"learning",label:"Vector databases; semantic vs keyword search; top-k retrieval"},
    {id:"w20t3",cat:"practice",label:"Manually compute cosine similarity between sentence embeddings"},
    {id:"w20t4",cat:"practice",label:"Store embeddings in a local vector DB; run a similarity query"},
    {id:"w20t5",cat:"build",label:"Mini build: semantic search over 10 sentences (retrieval only, no LLM)"},
  ],
  exitCriteria:[
    {id:"w20e1",label:"Can explain keyword search vs semantic search with an example"},
    {id:"w20e2",label:"Can chunk, embed, store, and retrieve top-k results unaided"},
  ]},
{ id:21, phaseId:9, title:"Project: RAG Chatbot & Generative AI Phase Wrap",
  goal:"Build a full RAG pipeline from raw documents to grounded answers; critically evaluate answers against source material.",
  projectId:10,
  tasks:[
    {id:"w21t1",cat:"learning",label:"Connecting retrieval to generation; grounding & citing sources"},
    {id:"w21t2",cat:"practice",label:"Test with in-scope and out-of-scope questions; check for hallucination"},
    {id:"w21t3",cat:"build",label:"Build Project 10 — RAG Chatbot"},
  ],
  exitCriteria:[
    {id:"w21e1",label:"Answers in-scope questions correctly, grounded in retrieved chunks"},
    {id:"w21e2",label:"Correctly declines/flags out-of-scope questions instead of hallucinating"},
    {id:"w21e3",label:"Has a written evaluation of at least 5 test questions"},
  ]},
{ id:22, phaseId:10, title:"Agentic AI Foundations & the Framework Landscape",
  goal:"Explain agentic vs non-agentic AI with an example, and implement basic tool-selection logic without a framework.",
  projectId:null,
  tasks:[
    {id:"w22t1",cat:"learning",label:"Agentic vs non-agentic AI; the agent loop (tool call, observe, plan)"},
    {id:"w22t2",cat:"learning",label:"Framework landscape: LangChain, LlamaIndex, AutoGen, CrewAI, LangGraph"},
    {id:"w22t3",cat:"practice",label:"Design a tool-selection decision flow on paper"},
    {id:"w22t4",cat:"build",label:"Mini build: plain-Python route_tool() picking between 2-3 dummy tools"},
  ],
  exitCriteria:[
    {id:"w22e1",label:"Can explain agentic vs non-agentic AI with a concrete example"},
    {id:"w22e2",label:"route_tool() correctly routes given different inputs"},
    {id:"w22e3",label:"Can name one good use case for each of the 5 frameworks"},
  ]},
{ id:23, phaseId:10, title:"Project: Informational Agent (Plain Python)",
  goal:"Build a complete tool-using agent loop from scratch, including graceful error handling and fallback behavior.",
  projectId:11,
  tasks:[
    {id:"w23t1",cat:"learning",label:"Full agent loop: understand → select tool → call → observe → format"},
    {id:"w23t2",cat:"practice",label:"Implement & test each tool function (weather/news/dictionary) in isolation"},
    {id:"w23t3",cat:"build",label:"Build Project 11 (v1) — Informational Agent, plain Python"},
  ],
  exitCriteria:[
    {id:"w23e1",label:"Correctly routes 3+ question types to the right tool"},
    {id:"w23e2",label:"Returns a clean fallback (not a crash) when a tool fails"},
    {id:"w23e3",label:"Response formatting reads naturally, not like raw API output"},
  ]},
{ id:24, phaseId:10, title:"Rebuilding the Agent with LangGraph",
  goal:"Build the same agent in both plain Python and LangGraph; articulate the trade-offs between the two.",
  projectId:11,
  tasks:[
    {id:"w24t1",cat:"learning",label:"LangGraph core concepts: nodes, edges, shared state"},
    {id:"w24t2",cat:"practice",label:"Map the plain-Python loop onto LangGraph nodes/edges"},
    {id:"w24t3",cat:"build",label:"Build Project 11 (v2) — same agent, reimplemented in LangGraph"},
    {id:"w24t4",cat:"build",label:"Write a plain-Python vs LangGraph comparison"},
  ],
  exitCriteria:[
    {id:"w24e1",label:"LangGraph version produces the same correct behavior as v1"},
    {id:"w24e2",label:"Can point to the node/edge that replaced each piece of the old loop"},
    {id:"w24e3",label:"Comparison names one concrete advantage and one concrete cost of LangGraph"},
  ]},
{ id:25, phaseId:10, title:"Capstone: Travel Planner Agent & Career Wrap",
  goal:"Design, build, and evaluate a multi-step, multi-tool, constraint-aware agent end to end.",
  projectId:12,
  tasks:[
    {id:"w25t1",cat:"learning",label:"Multi-step task decomposition; constraint satisfaction (budget)"},
    {id:"w25t2",cat:"practice",label:"Manually decompose the travel-planner problem before coding"},
    {id:"w25t3",cat:"build",label:"Build Project 12 — Travel Planner Agent (capstone)"},
    {id:"w25t4",cat:"build",label:"Finalize GitHub portfolio & README across all 12 projects"},
  ],
  exitCriteria:[
    {id:"w25e1",label:"Given destination/budget/duration, produces a day-by-day itinerary"},
    {id:"w25e2",label:"Itinerary respects the stated budget (or explains why it can't)"},
    {id:"w25e3",label:"Can defend every major design decision in the agent's graph"},
  ]},
];

const PROJECTS = [
  { id:1, weekIntroduced:3, name:"Student Report Card Generator",
    problem:"Given a student's ID, name, and marks per subject, produce a formatted report card showing average and letter grade.",
    features:["Input ID/name/marks per subject","Store marks in a dictionary","Calculate average & grade","Print a formatted report card","Support multiple students"],
    architecture:"User Input (ID, Name, Marks)\n      ↓\nStore in Dictionary\n      ↓\nCalculate Average & Grade\n      ↓\nPrint Formatted Report",
    input:"Student ID, name, subject:marks pairs (0-100)", output:"Formatted, aligned report card for one or more students",
    techStack:["Python"],
    tasks:[{id:"p1t1",label:"Design student data model (dict of dicts)"},{id:"p1t2",label:"Input loop for multiple students"},
      {id:"p1t3",label:"calculate_average() function"},{id:"p1t4",label:"calculate_grade() function"},
      {id:"p1t5",label:"print_report_card() formatted output"},{id:"p1t6",label:"Test with 3-5 students incl. edge cases"},
      {id:"p1t7",label:"(v2) JSON/CSV persistence between runs"},{id:"p1t8",label:"README with sample run"}],
    testing:["Student with zero subjects","Out-of-range mark (e.g. 150)","Duplicate student IDs"] },
  { id:2, weekIntroduced:3, name:"Personal Expense Tracker (v1)",
    problem:"Let a user log daily expenses by category and answer basic questions about their spending.",
    features:["Add expense (category+amount+date)","Store as list of dicts","Total spent","Highest expense","Filter by category"],
    architecture:"User Input (menu-driven CLI)\n      ↓\nStore in List of Dictionaries\n      ↓\nAggregate / Filter Functions\n      ↓\nConsole Output",
    input:"Category, amount, date per expense", output:"Printed totals, highest expense, category views",
    techStack:["Python"],
    tasks:[{id:"p2t1",label:"Design expense schema {category, amount, date}"},{id:"p2t2",label:"Menu loop: add/view/total/highest/filter/exit"},
      {id:"p2t3",label:"Implement each menu option as a function"},{id:"p2t4",label:"Test with a realistic week of sample expenses"},
      {id:"p2t5",label:"(v2) JSON file persistence between runs"},{id:"p2t6",label:"README with sample run"}],
    testing:["Zero expenses recorded","Negative amount rejected","Unrecognized category filter"] },
  { id:3, weekIntroduced:6, name:"Expense Tracker — API Version",
    problem:"Expose the Week 3 tracker's logic over HTTP so any client can use it.",
    features:["POST /expenses","GET /expenses","GET /expenses/highest","GET /expenses/category/{name}","GET /expenses/total"],
    architecture:"Client (Postman / curl / browser)\n      ↓\nFastAPI App\n      ↓\nPydantic Validation\n      ↓\nIn-Memory Store (list)\n      ↓\nJSON Response",
    input:"JSON body {category, amount, date}", output:"JSON responses with correct status codes",
    techStack:["FastAPI","Pydantic","Uvicorn","Postman"],
    tasks:[{id:"p3t1",label:"Define Pydantic schema"},{id:"p3t2",label:"Add endpoint"},{id:"p3t3",label:"List endpoint"},
      {id:"p3t4",label:"Highest-expense endpoint"},{id:"p3t5",label:"Validation & error handling"},
      {id:"p3t6",label:"Postman collection incl. failure cases"},{id:"p3t7",label:"(advanced) API-key check + pagination"},{id:"p3t8",label:"README"}],
    testing:["Missing field","Negative amount","Wrong data type"] },
  { id:4, weekIntroduced:9, name:"Expense Tracker — API + Database Version",
    problem:"Replace the in-memory store with real, durable persistence.",
    features:["Same endpoints as Project 3, backed by a real DB table"],
    architecture:"User\n  ↓\nFastAPI\n  ↓\nBusiness Logic\n  ↓\nDatabase\n  ↓\nResponse",
    input:"Same API contract as Project 3", output:"JSON, durable across restarts",
    techStack:["FastAPI","PostgreSQL/MySQL","SQLAlchemy / psycopg2","python-dotenv"],
    tasks:[{id:"p4t1",label:"Design expenses table schema"},{id:"p4t2",label:"DB connection/config via .env"},
      {id:"p4t3",label:"Data-access layer separate from route handlers"},{id:"p4t4",label:"Wire endpoints to DB layer"},
      {id:"p4t5",label:"Test persistence across a server restart"},{id:"p4t6",label:"(advanced) Update/delete endpoints, pagination, index"},{id:"p4t7",label:"README"}],
    testing:["Restart-and-verify persistence","Invalid DB input handling"] },
  { id:5, weekIntroduced:11, name:"Student Score Predictor (Regression)",
    problem:"Predict a student's exam score from study hours and other available features.",
    features:["Train regression model","Compare predicted vs actual","Evaluation report","Live prediction on new input"],
    architecture:"Dataset (CSV)\n      ↓\nClean & Split (train/test)\n      ↓\nTrain Regression Model\n      ↓\nPredict on Test Set → Evaluate (MSE/R²)\n      ↓\nAccept New Input → Predict Score",
    input:"CSV of historical study-hours/score data + live user input", output:"Evaluation report + predicted score",
    techStack:["pandas","scikit-learn","matplotlib"],
    tasks:[{id:"p5t1",label:"Load & inspect data"},{id:"p5t2",label:"Clean data"},{id:"p5t3",label:"Train/test split"},
      {id:"p5t4",label:"Train LinearRegression"},{id:"p5t5",label:"Compute MSE/R² on test set"},
      {id:"p5t6",label:"CLI step for new predictions"},{id:"p5t7",label:"(advanced) Compare vs Polynomial/RandomForest"},{id:"p5t8",label:"README"}],
    testing:["Prediction sanity at 0 hours","Prediction sanity at very high hours"] },
  { id:6, weekIntroduced:13, name:"Spam Email/SMS Classifier",
    problem:"Classify a message as spam or ham from its text alone.",
    features:["Preprocessing pipeline","Vectorization","Trained classifier","Test on unseen messages","Full metrics report"],
    architecture:"Raw Messages\n      ↓\nClean & Preprocess Text\n      ↓\nVectorize (TF-IDF / BoW)\n      ↓\nTrain Classifier\n      ↓\nEvaluate (Accuracy/Precision/Recall/Confusion Matrix)\n      ↓\nPredict on New Message",
    input:"Labeled spam/ham dataset", output:"Metrics report + predict(message) utility",
    techStack:["pandas","scikit-learn"],
    tasks:[{id:"p6t1",label:"Load dataset"},{id:"p6t2",label:"Clean text"},{id:"p6t3",label:"Train/test split"},
      {id:"p6t4",label:"Vectorize (fit on train only)"},{id:"p6t5",label:"Train classifier"},
      {id:"p6t6",label:"Compute full metrics suite"},{id:"p6t7",label:"predict() utility for new messages"},
      {id:"p6t8",label:"(advanced) Compare NB vs LogReg vs SVM by F1"},{id:"p6t9",label:"README"}],
    testing:["Short messages","Innocent messages with spam-like words"] },
  { id:7, weekIntroduced:15, name:"Handwritten Digit Recognizer (MNIST)",
    problem:"Recognize handwritten digits (0-9) from images.",
    features:["Load MNIST","Preprocess","Train NN","Predict unseen images","Evaluate accuracy (~90%+ target)"],
    architecture:"MNIST Images (28x28)\n      ↓\nNormalize & Flatten/Reshape\n      ↓\nNeural Network (Dense or Conv2D)\n      ↓\nSoftmax Output (10 classes)\n      ↓\nPredict Digit + Evaluate Accuracy",
    input:"MNIST train/test images & labels", output:"Predicted digit class + accuracy metric",
    techStack:["TensorFlow/Keras","numpy","matplotlib"],
    tasks:[{id:"p7t1",label:"Load MNIST via keras.datasets"},{id:"p7t2",label:"Normalize/reshape"},
      {id:"p7t3",label:"Build Sequential model"},{id:"p7t4",label:"Compile (optimizer/loss/metrics)"},
      {id:"p7t5",label:"Fit with validation split"},{id:"p7t6",label:"Evaluate on test set"},
      {id:"p7t7",label:"Visualize correct & incorrect predictions"},{id:"p7t8",label:"(advanced) Swap in a Conv2D CNN"},{id:"p7t9",label:"README"}],
    testing:["Inspect commonly-confused digit pairs (e.g. 4 vs 9)"] },
  { id:8, weekIntroduced:17, name:"Sentiment Analysis (Text Classification, DL)",
    problem:"Classify text as positive or negative sentiment using a neural approach.",
    features:["Preprocess text","Embeddings","RNN/LSTM model","Predict unseen text","Evaluate"],
    architecture:"Labeled Text Data\n      ↓\nClean & Tokenize\n      ↓\nPad Sequences\n      ↓\nEmbedding Layer\n      ↓\nLSTM / RNN Layer\n      ↓\nDense + Sigmoid Output\n      ↓\nPredict Sentiment + Evaluate",
    input:"Labeled positive/negative text dataset (e.g. IMDB)", output:"Sentiment label + confidence + metrics",
    techStack:["TensorFlow/Keras","scikit-learn","matplotlib"],
    tasks:[{id:"p8t1",label:"Load & clean dataset"},{id:"p8t2",label:"Tokenize & pad sequences"},
      {id:"p8t3",label:"Build Embedding→LSTM→Dense model"},{id:"p8t4",label:"Train with validation split"},
      {id:"p8t5",label:"Evaluate full metric suite"},{id:"p8t6",label:"predict_sentiment() utility"},
      {id:"p8t7",label:"(advanced) Try Bidirectional LSTM/GRU"},{id:"p8t8",label:"README"}],
    testing:["Ambiguous/sarcastic sentences"] },
  { id:9, weekIntroduced:19, name:"Resume Screening Application",
    problem:"Automatically compare a candidate resume against a job description and recommend select/reject.",
    features:["Extract structured resume details","Extract structured JD requirements","Compare","Output decision + reasoning"],
    architecture:"Resume (text)        Job Description (text)\n   ↓                        ↓\nLLM Extraction        LLM Extraction\n   ↓                        ↓\nStructured Candidate   Structured Requirements\n         ↓        ↓\n      Comparison Logic\n            ↓\n  Select / Reject + Reasoning",
    input:"Resume text + job description text", output:"JSON verdict {decision, matched_skills, missing_skills, reasoning}",
    techStack:["LLM API","Python","Pydantic"],
    tasks:[{id:"p9t1",label:"Design resume JSON schema"},{id:"p9t2",label:"Write & test resume extraction prompt"},
      {id:"p9t3",label:"Design JD JSON schema"},{id:"p9t4",label:"Write & test JD extraction prompt"},
      {id:"p9t5",label:"Write comparison logic"},{id:"p9t6",label:"Format final decision output"},
      {id:"p9t7",label:"Test across several resume/JD pairs"},{id:"p9t8",label:"(advanced) Batch-rank multiple resumes / FastAPI wrap"},{id:"p9t9",label:"README"}],
    testing:["Strong match","Weak match","Borderline case","Malformed resume"] },
  { id:10, weekIntroduced:21, name:"RAG Chatbot",
    problem:"Answer questions grounded in user-provided documents rather than general LLM knowledge alone.",
    features:["Load","Clean","Chunk","Embed","Store","Retrieve top-k","Generate grounded answer"],
    architecture:"Documents\n   ↓\nLoader\n   ↓\nChunking\n   ↓\nEmbeddings\n   ↓\nVector DB\n   ↓\nRetriever\n   ↓\nTop-K Context\n   ↓\nLLM\n   ↓\nAnswer",
    input:"2-5 user documents (PDF/txt/markdown)", output:"Grounded answer, optionally with source citations",
    techStack:["LLM API","Embeddings model","ChromaDB / FAISS"],
    tasks:[{id:"p10t1",label:"Pick 2-5 sample documents"},{id:"p10t2",label:"Build a loader"},
      {id:"p10t3",label:"Clean text"},{id:"p10t4",label:"Chunk with overlap"},
      {id:"p10t5",label:"Embed & store with metadata"},{id:"p10t6",label:"Build query flow (embed → retrieve → prompt → answer)"},
      {id:"p10t7",label:"Build a small Q&A evaluation set"},{id:"p10t8",label:"(advanced) Re-ranking / hybrid search / chat memory"},{id:"p10t9",label:"README"}],
    testing:["In-scope questions","Out-of-scope questions","Ambiguous questions"] },
  { id:11, weekIntroduced:23, name:"Informational Agent (Plain Python → LangGraph)",
    problem:"Answer natural-language informational questions by routing to the right external tool/API.",
    features:["Intent understanding","Tool selection","Tool execution","Result formatting","Graceful failure + fallback"],
    architecture:"User\n  ↓\nAgent\n  ↓\nDecision / Tool Selection\n  ↓\nTool / API\n  ↓\nObservation\n  ↓\nNext Step\n  ↓\nFinal Response",
    input:"Natural-language question (weather / news / dictionary)", output:"Natural-language answer or graceful fallback",
    techStack:["Python","requests","LLM API","LangGraph (v2)"],
    tasks:[{id:"p11t1",label:"Define each tool as a plain function"},{id:"p11t2",label:"Write routing step (v1: plain Python)"},
      {id:"p11t3",label:"Write execution step with try/except + fallback"},{id:"p11t4",label:"Write response-formatting step"},
      {id:"p11t5",label:"Wire router → executor → formatter loop (v1 complete)"},
      {id:"p11t6",label:"Define LangGraph state schema (v2)"},{id:"p11t7",label:"Rebuild as LangGraph nodes/edges (v2 complete)"},
      {id:"p11t8",label:"Write v1 vs v2 comparison notes"},{id:"p11t9",label:"(advanced) 4th tool + conversation memory"},{id:"p11t10",label:"README"}],
    testing:["Valid query per tool","Ambiguous query","Deliberately broken endpoint"] },
  { id:12, weekIntroduced:25, name:"Travel Planner Agent (Capstone)",
    problem:"Given destination, budget, and duration, produce a realistic day-by-day itinerary.",
    features:["Task decomposition","Per-category option gathering","Budget-aware combination","Structured day-by-day output"],
    architecture:"User (destination, budget, duration)\n      ↓\nPlanner Node (decompose)\n      ↓\nTransport | Accommodation | Food | Sightseeing\n      ↓\nBudget-Aware Combiner Node\n      ↓\nStructured Day-by-Day Itinerary",
    input:"Destination, budget, duration", output:"Day-by-day itinerary with estimated cost per item vs budget",
    techStack:["LangGraph","LLM API","requests / sample data"],
    tasks:[{id:"p12t1",label:"Define agent state schema"},{id:"p12t2",label:"Build planner node"},
      {id:"p12t3",label:"Build 4 tool-gathering nodes (transport/stay/food/sights)"},
      {id:"p12t4",label:"Build combiner/budget node"},{id:"p12t5",label:"Wire the graph incl. conditional edges"},
      {id:"p12t6",label:"Run end to end, format output"},
      {id:"p12t7",label:"(advanced) Mid-plan replanning + visual summary"},{id:"p12t8",label:"README + portfolio writeup"}],
    testing:["Very tight budget","Generous budget","Unusual destination"] },
];

const SKILLS = [
  {id:"python", name:"Python"}, {id:"fastapi", name:"FastAPI"}, {id:"rest-apis", name:"REST APIs"},
  {id:"postgresql", name:"PostgreSQL"}, {id:"sql", name:"SQL"}, {id:"db-design", name:"Database Design"},
  {id:"ml", name:"Machine Learning"}, {id:"sklearn", name:"Scikit-learn"}, {id:"dl", name:"Deep Learning"},
  {id:"tensorflow", name:"TensorFlow"}, {id:"llms", name:"LLMs"}, {id:"prompt-eng", name:"Prompt Engineering"},
  {id:"embeddings", name:"Embeddings"}, {id:"vector-db", name:"Vector Databases"}, {id:"rag", name:"RAG"},
  {id:"langchain", name:"LangChain"}, {id:"langgraph", name:"LangGraph"}, {id:"ai-agents", name:"AI Agents"},
  {id:"tool-calling", name:"Tool Calling"}, {id:"api-integration", name:"API Integration"},
];

const SKILL_STATUS_LEVELS = ["not-started","learning","practiced","project-experience","confident","interview-ready"];
const SKILL_STATUS_LABELS = {
  "not-started":"Not Started","learning":"Learning","practiced":"Practiced",
  "project-experience":"Project Experience","confident":"Confident","interview-ready":"Interview Ready"
};

const ASSESSMENTS = [
  { id:1, phaseId:1, name:"Phase 1 Assessment — Python Foundations", passThreshold:70,
    items:[
      {id:"a1i1",label:"Write a function-based program from a new spec in under 30 minutes"},
      {id:"a1i2",label:"Correctly use if/elif/else, loops, and functions together"},
      {id:"a1i3",label:"Choose the right collection type (list/tuple/dict) for a new problem"},
      {id:"a1i4",label:"Explain the difference between = and =="},
      {id:"a1i5",label:"Refactor a script into functions without guidance"},
    ]},
  { id:2, phaseId:2, name:"Phase 2 Assessment — Python Applications", passThreshold:70,
    items:[
      {id:"a2i1",label:"Build a new small CLI tool from a fresh one-paragraph spec"},
      {id:"a2i2",label:"Add input validation to a program unaided"},
      {id:"a2i3",label:"Test an empty-data edge case correctly"},
      {id:"a2i4",label:"Report Card Generator fully functional"},
      {id:"a2i5",label:"Expense Tracker fully functional"},
    ]},
  { id:3, phaseId:3, name:"Phase 3 Assessment — API / FastAPI", passThreshold:70,
    items:[
      {id:"a3i1",label:"Build & document (Swagger) a 3-endpoint API for a new resource"},
      {id:"a3i2",label:"Validate request bodies with Pydantic"},
      {id:"a3i3",label:"Return correct status codes for success and failure"},
      {id:"a3i4",label:"Test all routes in Postman incl. error paths"},
    ]},
  { id:4, phaseId:4, name:"Phase 4 Assessment — API-Powered App", passThreshold:70,
    items:[
      {id:"a4i1",label:"Add Expense API implemented"},
      {id:"a4i2",label:"Get Expenses API implemented"},
      {id:"a4i3",label:"Highest Expense API implemented"},
      {id:"a4i4",label:"Postman testing complete incl. failure cases"},
      {id:"a4i5",label:"Error handling in place"},
      {id:"a4i6",label:"Project completed"},
    ]},
  { id:5, phaseId:5, name:"Phase 5 Assessment — SQL + Database", passThreshold:70,
    items:[
      {id:"a5i1",label:"Find highest-scoring student"},
      {id:"a5i2",label:"Find average score"},
      {id:"a5i3",label:"Group students by grade"},
      {id:"a5i4",label:"Filter students (WHERE)"},
      {id:"a5i5",label:"Sort students (ORDER BY)"},
      {id:"a5i6",label:"Use aggregate functions"},
      {id:"a5i7",label:"Perform full CRUD from Python"},
    ]},
  { id:6, phaseId:6, name:"Phase 6 Assessment — End-to-End Application", passThreshold:70,
    items:[
      {id:"a6i1",label:"Rebuild 'highest expense' as a SQL-sorted top-N endpoint"},
      {id:"a6i2",label:"Data survives a server restart"},
      {id:"a6i3",label:"Credentials managed via environment variables, not hardcoded"},
      {id:"a6i4",label:"Full CRUD API backed by a real database"},
    ]},
  { id:7, phaseId:7, name:"Phase 7 Assessment — Machine Learning", passThreshold:70,
    items:[
      {id:"a7i1",label:"Build & evaluate a model on an unfamiliar dataset in a time box"},
      {id:"a7i2",label:"Avoid data leakage (fit vectorizer/scaler on train split only)"},
      {id:"a7i3",label:"Correctly interpret precision/recall trade-off"},
      {id:"a7i4",label:"Compare two algorithms and justify the better one"},
      {id:"a7i5",label:"Score Predictor project completed"},
      {id:"a7i6",label:"Spam Classifier project completed"},
    ]},
  { id:8, phaseId:8, name:"Phase 8 Assessment — Deep Learning", passThreshold:70,
    items:[
      {id:"a8i1",label:"Train & evaluate a new NN on an unfamiliar image or text dataset"},
      {id:"a8i2",label:"Normalize input data correctly"},
      {id:"a8i3",label:"Use a validation split to monitor overfitting"},
      {id:"a8i4",label:"Add dropout and compare before/after validation curves"},
      {id:"a8i5",label:"Digit Recognizer project completed"},
      {id:"a8i6",label:"Sentiment Analysis project completed"},
    ]},
  { id:9, phaseId:9, name:"Phase 9 Assessment — Generative AI (Non-Agentic)", passThreshold:70,
    items:[
      {id:"a9i1",label:"Build a mini RAG bot over new documents with a written evaluation"},
      {id:"a9i2",label:"Handle the 'answer not in documents' case without hallucinating"},
      {id:"a9i3",label:"Add source citations to RAG answers"},
      {id:"a9i4",label:"Resume Screener project completed"},
      {id:"a9i5",label:"RAG Chatbot project completed"},
    ]},
  { id:10, phaseId:10, name:"Phase 10 Assessment — Agentic AI", passThreshold:70,
    items:[
      {id:"a10i1",label:"Design & build a new 2-tool agent for an unfamiliar use case"},
      {id:"a10i2",label:"Defend the agent's design choices in writing"},
      {id:"a10i3",label:"Add fallback/error handling around every tool call"},
      {id:"a10i4",label:"Informational Agent (both versions) completed"},
      {id:"a10i5",label:"Travel Planner Agent (capstone) completed"},
    ]},
];
