-- Run this in the Supabase SQL editor.
create table if not exists public.tracker_state (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade unique,
  state jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.tracker_state enable row level security;

drop policy if exists "Users can select their own tracker state" on public.tracker_state;
drop policy if exists "Users can insert their own tracker state" on public.tracker_state;
drop policy if exists "Users can update their own tracker state" on public.tracker_state;

create policy "Users can select their own tracker state"
  on public.tracker_state for select to authenticated
  using (auth.uid() = user_id);

create policy "Users can insert their own tracker state"
  on public.tracker_state for insert to authenticated
  with check (auth.uid() = user_id);

create policy "Users can update their own tracker state"
  on public.tracker_state for update to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
